---
output: 
  html_document:
    includes:
      in_header: test1.html
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(learnr)
knitr::opts_chunk$set(echo = FALSE)
```




### Quiz

*You can include any number of single or multiple choice questions as a quiz. Use the `question` function to define a question and the `quiz` function for grouping multiple questions together.*

Some questions to verify that you understand the purposes of various base and recommended R packages:

```{r quiz}
quiz(
  question("Wie werden in Excel Spalten identifiziert?",
    answer("mit Zahlen"),
    answer("mit Buchstaben", correct = TRUE),
    answer("gar nicht")
  ),
  question("wodurch ist in Excel eine einzelne Zelle identifiziert?",
    answer("durch eine Spalten- und eine Zeilenkoordinate", correct = TRUE),
    answer("durch eine Zeilen- und eine Spaltenkoordinate"),
    answer("nur durch eine Zeilenkoordinate"),
    answer("nur durch eine Spaltenkoordinate")
  )
)
```

<div data-iframe-height></div>
